name: pg
channels:
  - gimli
  - conda-forge
  - defaults

dependencies:
  - aiohappyeyeballs
  - aiohttp
  - aiosignal
  - appnope
  - asttokens
  - attrs
  - blosc
  - boost
  - brotli
  - brotli-bin
  - brotli-python
  - bzip2
  - c-ares
  - ca-certificates
  - cairo
  - certifi
  - cffi
  - charset-normalizer
  - colorama
  - comm
  - contourpy
  - cycler
  - cyrus-sasl
  - debugpy
  - decorator
  - double-conversion
  - exceptiongroup
  - executing
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - fonttools
  - freetype
  - frozenlist
  - glib
  - glib-tools
  - gmp
  - graphite2
  - gst-plugins-base
  - gstreamer
  - h2
  - harfbuzz
  - hdf4
  - hdf5
  - hpack
  - hyperframe
  - icu
  - idna
  - importlib-metadata
  - iniconfig
  - ipykernel
  - ipython
  - ipython_pygments_lexers
  - jedi
  - jsoncpp
  - jupyter_client
  - jupyter_core
  - kiwisolver
  - krb5
  - lcms2
  - lerc
  - libaec
  - libamd
  - libblas
  - libboost
  - libboost-devel
  - libboost-headers
  - libboost-python
  - libboost-python-devel
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libbtf
  - libcamd
  - libcblas
  - libccolamd
  - libcholmod
  - libclang-cpp17
  - libclang-cpp19.1
  - libclang13
  - libcolamd
  - libcurl
  - libcxsparse
  - libcxx
  - libdeflate
  - libedit
  - libev
  - libexpat
  - libffi
  - libfreetype
  - libgfortran
  - libgfortran5
  - libglib
  - libhwloc
  - libiconv
  - libintl
  - libintl-devel
  - libjpeg-turbo
  - libklu
  - liblapack
  - libldl
  - libllvm17
  - libllvm19
  - libllvm21
  - liblzma
  - liblzma-devel
  - libnetcdf
  - libnghttp2
  - libntlm
  - libogg
  - libopenblas
  - libopus
  - libparu
  - libpng
  - libpq
  - librbio
  - libsodium
  - libspex
  - libspqr
  - libsqlite
  - libssh2
  - libsuitesparseconfig
  - libtheora
  - libtiff
  - libumfpack
  - libvorbis
  - libwebp-base
  - libxcb
  - libxml2
  - libzip
  - libzlib
  - llvm-openmp
  - loguru
  - lz4-c
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - metis
  - mpfr
  - msgpack-python
  - multidict
  - munkres
  - ncurses
  - nest-asyncio
  - nlohmann_json
  - nspr
  - nss
  - numpy
  - openblas
  - openjpeg
  - openldap
  - openssl
  - packaging
  - parso
  - pcre2
  - pexpect
  - pgcore
  - pickleshare
  - pillow
  - pip
  - pixman
  - platformdirs
  - pluggy
  - ply
  - pooch
  - proj
  - prompt-toolkit
  - propcache
  - psutil
  - pthread-stubs
  - ptyprocess
  - pugixml
  - pure_eval
  - pycparser
  - pygimli
  - pygments
  - pyparsing
  - pyqt
  - pyqt5-sip
  - pysocks
  - pytest
  - python
  - python-dateutil
  - python-gil
  - python_abi
  - pyvista
  - pyzmq
  - qhull
  - qt-main
  - qt6-main
  - readline
  - requests
  - scipy
  - scooby
  - setuptools
  - sip
  - six
  - snappy
  - sqlite
  - stack_data
  - suitesparse
  - tbb
  - tk
  - toml
  - tomli
  - tornado
  - tqdm
  - traitlets
  - typing-extensions
  - typing_extensions
  - unicodedata2
  - urllib3
  - utfcpp
  - vtk-base
  - wcwidth
  - wheel
  - wslink
  - xorg-libxau
  - xorg-libxdmcp
  - xz
  - xz-gpl-tools
  - xz-tools
  - yarl
  - zeromq
  - zipp
  - zlib
  - zstandard
  - zstd

  - pip:
      - anyio
      - argon2-cffi
      - argon2-cffi-bindings
      - arrow
      - async-lru
      - audioread
      - babel
      - beautifulsoup4
      - bleach
      - defusedxml
      - disba
      - fastjsonschema
      - filelock
      - fqdn
      - fsspec
      - h11
      - httpcore
      - httpx
      - ipympl
      - ipywidgets
      - isoduration
      - jinja2
      - joblib
      - json5
      - jsonpointer
      - jsonschema
      - jsonschema-specifications
      - jupyter-events
      - jupyter-lsp
      - jupyter-server
      - jupyter-server-proxy
      - jupyter-server-terminals
      - jupyterlab
      - jupyterlab-pygments
      - jupyterlab-server
      - jupyterlab-widgets
      - lark
      - lazy-loader
      - librosa
      - llvmlite
      - lxml
      - markdown-it-py
      - markupsafe
      - mdurl
      - meshio
      - mistune
      - more-itertools
      - mpmath
      - nbclient
      - nbconvert
      - nbformat
      - networkx
      - noisereduce
      - notebook-shim
      - numba
      - obspy
      - pandas
      - pandocfilters
      - prometheus-client
      - python-json-logger
      - pytz
      - pyyaml
      - referencing
      - rfc3339-validator
      - rfc3986-validator
      - rfc3987-syntax
      - rich
      - rpds-py
      - scikit-learn
      - send2trash
      - simpervisor
      - sniffio
      - soundfile
      - soupsieve
      - soxr
      - sqlalchemy
      - sympy
      - terminado
      - threadpoolctl
      - tinycss2
      - torch
      - trame
      - trame-client
      - trame-common
      - trame-jupyter-extension
      - trame-server
      - trame-vtk
      - trame-vuetify
      - types-python-dateutil
      - tzdata
      - uri-template
      - webcolors
      - webencodings
      - websocket-client
      - widgetsnbextension
